### ISSUE TITLE
Create the basic Calculator

### ISSUE THREAD

**Issue by Isha307** [Isha307/Calculator#3]
You can create a calculator using any language that can perform basic operation like addition, subtraction, Multiplication and division that take input from the user.

**Comment by nidh-ish** [comment]
I want to work on this issue.

**Comment by 96RadhikaJadhav** [comment]
@Isha307 I would like to do it in python, java, JavaScript. Can I work on it?

**Comment by Isha307** [comment]
> @Isha307 I would like to do it in python, java, JavaScript. Can I work on it?

Yes, I am assigning it to you.

**Comment by Isha307** [comment]
> I want to work on this issue.

You can work on it, I am assigning it to you too.

**Comment by 96RadhikaJadhav** [comment]
@Isha307 I have added program for java. Please check and let me know if any changes needed.
For javascript I will add basic calculator app using HTML,CSS and JS. The code is bit long, it will take some time. So will create a PR tomorrow.

**Comment by Isha307** [comment]
> @Isha307 I have added program for java. Please check and let me know if any changes needed.
> For javascript I will add basic calculator app using HTML,CSS and JS. The code is bit long, it will take some time. So will create a PR tomorrow.

Java file is working fine.

**Comment by emMercado** [comment]
hi! i have calculator in php. Please check and let me know if any changes needed.

**Comment by aditisingh2412** [comment]
Hey, I'm a newbie :) Can I work on this issue? Is it opened?

**Comment by Isha307** [comment]
> Hey, I'm a newbie :) Can I work on this issue? Is it opened?

Yes

**Comment by aditisingh2412** [comment]
> > Hey, I'm a newbie :) Can I work on this issue? Is it opened?
> 
> Yes

Which language is left to make the calculator?

**Comment by Isha307** [comment]
> > > Hey, I'm a newbie :) Can I work on this issue? Is it opened?
> > 
> > 
> > Yes
> 
> Which language is left to make the calculator?

You can try java

**Comment by aditisingh2412** [comment]
> > > > Hey, I'm a newbie :) Can I work on this issue? Is it opened?
> > > 
> > > 
> > > Yes
> > 
> > 
> > Which language is left to make the calculator?
> 
> You can try java

C/C++ ?

**Comment by Isha307** [comment]
> > > > > Hey, I'm a newbie :) Can I work on this issue? Is it opened?
> > > > 
> > > > 
> > > > Yes
> > > 
> > > 
> > > Which language is left to make the calculator?
> > 
> > 
> > You can try java
> 
> C/C++ ?

yes, you can try C++.

**Comment by aditisingh2412** [comment]
> > > > > > Hey, I'm a newbie :) Can I work on this issue? Is it opened?
> > > > > 
> > > > > 
> > > > > Yes
> > > > 
> > > > 
> > > > Which language is left to make the calculator?
> > > 
> > > 
> > > You can try java
> > 
> > 
> > C/C++ ?
> 
> yes, you can try C++.

Ok, assign this to me.

**Comment by AdityaVSM** [comment]
I can do it using C++, assign it to me

**Comment by aditisingh2412** [comment]
> > > > > > > Hey, I'm a newbie :) Can I work on this issue? Is it opened?
> > > > > > 
> > > > > > 
> > > > > > Yes
> > > > > 
> > > > > 
> > > > > Which language is left to make the calculator?
> > > > 
> > > > 
> > > > You can try java
> > > 
> > > 
> > > C/C++ ?
> > 
> > 
> > yes, you can try C++.
> 
> Ok, assign this to me.

I'm done. You can look into it and tell me the changes if any :)

**Comment by kcabrera14** [comment]
Hello ! Can I work on this issue in Python?

**Comment by kcabrera14** [comment]
Hello @Isha307 ! Could I contribute on this issue by creating a Python calculator ? if you could assign me that would be great.

**Comment by Isha307** [comment]
> Hello @Isha307 ! Could I contribute on this issue by creating a Python calculator ? if you could assign me that would be great.

Okk

**Comment by kcabrera14** [comment]
> > Hello @Isha307 ! Could I contribute on this issue by creating a Python calculator ? if you could assign me that would be great.
> 
> Okk

I have completed the python calculator. Feel free to let me know if I should make any modifications :)
